config/routes.rb
Rails.application.routes.draw do
  get 'avatars/create'
  # get 'users/show'
  root to: 'events#index'

  devise_for :users
  resources :attendances
  resources :events
  post 'events/subscribe/:id', to: 'events#subscribe', as: 'subscribe'

  resources :users do
    resources :avatars, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :event, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
  # Un événement a plusieurs participations, et plusieurs participants (utilisateurs) au travers des participations.
  has_many :attendances
  has_many :users, through: :attendances

  # Un événement appartient à un administrateur (utilisateur).
  belongs_to :admin, class_name: 'User'

  has_one_attached :avatar_event

  # presence obligatoire
  validates :start_date, :duration, :title, :description, :price, :location,
  presence: true

  validates :title, 
  length: { minimum: 5, maximum:  140}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances

  has_many :events, foreign_key: 'admin_id', class_name: 'Event'

  has_one_attached :avatar

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  skip_before_action :verify_authenticity_token

  # order by most recents first
  def index
    @events = Event.all.order('created_at DESC')
  end

  def new 
    @event = Event.new
  end 

  def show 
    @event = Event.find(params['id'])
  end

  def create
    @event = Event.new(admin: current_user,
                       title: params[:event][:title],
                       start_date: params[:event][:start_date],
                       duration: params[:event][:duration],
                       description: params[:event][:description],
                       price: params[:event][:price],
                       location: params[:event][:location])
      # @event.avatar_event.attach(params[:avatar_event])
                       
    if @event.save
      flash[:success] = "L'évènement a été créé avec succès!"
      redirect_to root_path
    else
      flash[:error] = "L'évènement n'a pas pu être créé..."
      render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    event_params = params.require(:event).permit(:title, :description, :avatar)
    if @event.update(event_params)
      flash[:success] = "L'évènement a été modifié avec succès!"
      redirect_to events_path
    else
      flash[:error] = "L'évènement n'a pas pu être modifié..."
      render :edit
    end
  end

  def subscribe 
   
    @event = Event.find(params[:id])
    if @event.users.include? current_user 
      flash[:error] = "Vous participez déjà à l'évènement"
      redirect_to event_path
      return
    end  

    @amount = @event.price

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
 
    @event.users << current_user
    flash[:success] = "Vous participez à l'évènement"
    redirect_to event_path

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to event_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
   @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/avatars/create.html.erb
<h1>Avatars#create</h1>
<p>Find me in app/views/avatars/create.html.erb</p>

app/views/events/_events_index.html.erb
<div class="card-deck">
  <% @events.each do |event|%>
    <div class="col-lg-3 col-md-6 mb-3">
      <div class="card text-center my-3 border-primary mb-3" style="max-width: 18rem;">
      <div class="card-header"><h5><%= event.title%></h5></div>
        <div class="card-body ">
          <h5 class="card-title ">Evènement n° <%= event.id %></h5>
          <h6 class="card-title"> Lieu de l'évènement: <%= event.location %></h6>
          <h6 class="card-title">Prix: <%= event.price %></h6>
          <a href="<%= event_path(event.id) %>" class="btn btn-success text-center">Voir l'évenement</a><br><br>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_jumbotron.html.erb
<div class="jumbotron text-center background-big-jumbotron">
  <h2 class="display-4">Bienvenue sur Eventbrite!</h2>
  <p class="lead">Ce site vous permet de trouver les évènements qui ont lieu autour de chez vous ou ailleurs!</p>
  <hr class="my-4">
  <p>Vous pouvez aussi créer votre propre évènement:</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="<%= new_event_path %>" role="button">Créer un évènement</a>
  </p>
</div>

app/views/events/_new_event.html.erb
<h2 class="card-title text-center m-3">Crée ton évènement</h2>
<div class="container col-6">

  <%= form_for @event do |f| %>

    <!-- Flash message -->
    <% if @event.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label "Titre" %><br />
      <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "Nom de l'évènement", class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label "Date de l'évènement" %><br />
      <%= f.datetime_field :start_date, autocomplete: "start_date", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Durée de l'évènement (en min)" %><br />
      <%= f.text_field :duration, autocomplete: "duration", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Description" %><br />
      <%= f.text_area :description, autocomplete: "description", placeholder:"Description de l'évènement", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Lieu" %><br />
      <%= f.text_field :location, autocomplete: "location", placeholder:"Lieu de l'évènement", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Prix (cents)" %><br />
      <%= f.text_field :price, autocomplete: "price", placeholder:"Prix de l'inscription", class: "form-control" %>
    </div>
    
   <div class="actions">
      <%= f.submit "Créer l'évènement", {class: 'btn btn-info btn-block'}%>
    </div>
  
<!-- 
    <div class="form-group">
      <%= f.label "Ajouter une image" %><br />
      <%= form_tag multipart: true do %>
      <%= file_field_tag :avatar_event %>
      <%= submit_tag "mettre à jour" %>
      <% end %>
    </div>
-->
<% end %>
</div>

app/views/events/_participants_list.html.erb
<h3 class="text-center">Liste des participants</h3>

<div class="container" style="justify-content: center; width:700px">

  <div class="p-3 bg-white rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0">Participants</h6>
    <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1722ce8c3d2%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1722ce8c3d2%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.296875%22%20y%3D%2216.9%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
      <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">@username</strong>
        user.description : blablablablabla
      </p>
    </div>
  </div>
</div>

app/views/events/_show_event.html.erb
<div class="card-deck justify-content-center">
    <div class="col-lg-4 col-md-6 mb-3">
      <div class="card border-primary mt-5 mb-3" style="max-width: 25rem;">
      <div class="card-header text-center"><h5><%= @event.title%></h5></div>
        <div class="card-body">
          <h5 class="card-title text-center">Evènement n° <%= @event.id %></h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Début: <%= @event.start_date %></li>
              <li class="list-group-item">Prix: <%= @event.price %> cents</li>
              <li class="list-group-item">Durée: <%= @event.duration %></li>
              <li class="list-group-item">Lieu de l'évènement: <%= @event.location %></li>
              <li class="list-group-item">Créé par l'utilisateur:  <%= @event.admin.email %></li>
            </ul>
          
          <div class="card-footer text-muted text-center">
            <%= form_tag subscribe_path do %>
              <article>
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                <% end %>
                <label class="amount">
                  <p>Pour rejoindre l'évènement, vous devez procéder au paiement:</p>
                  <span>Montant: <%= @event.price.to_f / 100 %>€</span>
                </label>
              </article>


              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="A month's subscription"
                      data-amount="<%= @event.price %>"
                      data-currency="eur"
                      data-locale="auto"></script>
            <% end %>

            <% if current_user == @event.admin %>
              <a href="<%= edit_event_path(@event.id) %>" class="btn btn-outline-secondary text-center ml-3 mt-2">Editer l'évènement</a>
              <a href="<%= event_path(@event.id) %>" class="btn btn-danger text-center ml-3 mt-2" data-confirm="are you sure?" data-method="DELETE">Supprimer l'évènement</a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

<%= render 'participants_list'%>

app/views/events/create.html.erb
create events

app/views/events/edit.html.erb
<div class="ml-5 mr-5">
  <h3 class="mb-4 mt-4">Editer l'évènement</h3>
  <%= form_for @event do |f| %>
    <div class="form-group">
      <label>Titre de l'évènement</label>
      <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
    <label>Description de l'évènement</label>
      <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class="form-group">
    <button type="subimit" class="btn btn-outline-info">Editer l'évènement</button>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<%= render 'events/jumbotron'%>
<%= render 'events/events_index'%>

app/views/events/new.html.erb
<%= render 'new_event' %>
 

app/views/events/show.html.erb
<%= render 'show_event'%>

app/views/layouts/_footer.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="vendor/assets/stylesheets/bootstrap.css">
    <!-- My CSS -->
    <link rel="stylesheet" href="app/assets/stylesheets/style.css">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/bc256b04c3.js" crossorigin="anonymous"></script>

    <title>Kit UI Eventbrite</title>
  </head>
  <body>


    <footer class="py-3 bg-success mt-4" style="bottom: 0;left: 0;right:0;">
      <div class="container">
        <p class="m-0 text-center"><strong>Copyright &copy; Eventbrite 2020</strong></p>
      </div>
      <!-- /.container -->
    </footer>
    
      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>

</html>

app/views/layouts/_navbar.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <%# <link rel="stylesheet" href="vendor/assets/stylesheets/bootstrap.css">
    <!-- My CSS -->
    <link rel="stylesheet" href="app/assets/stylesheets/style.css"> %>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/bc256b04c3.js" crossorigin="anonymous"></script>

    <title>Kit UI Eventbrite</title>
  </head>
  <body>

<% if user_signed_in? %> 

    <nav class="navbar navbar-expand-lg" >
      <a class="navbar-brand text-white" href="<%= root_path %>">Eventbrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-white" href="<%= new_event_path %>">Créer un évènement <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
        </ul>
    
      <div class="btn-group">
        <button type="button" class="nav-item btn btn-default text-white">Mon profile</button>
        <button type="button" class="btn btn-default dropdown-toggle text-white" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" role="menu" >
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Editer mon profile</a>
          <a class="dropdown-item" href="<%= user_path(current_user) %>">Voir mon profile</a>
          <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">Se déconnecter</a>
        </div>
      </div>
     </div>
    </nav>

    <% else %>
  <nav class="navbar navbar-expand-lg">
    <div class="btn-group">
      <button type="button" class="btn btn-default text-white">Connexion</button>
      <button type="button" class="btn btn-default dropdown-toggle text-white" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown" role="menu" >
        <a class="dropdown-item" href="<%= new_user_registration_path %>"> S'inscrire</a>
        <a class="dropdown-item" href="<%= new_user_session_path %>"> Se connecter</a>
      </div>
    </div>
  </nav>


<% end %> 
  
      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteProject2020</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
    <% end %>

    <% if flash[:danger] %>
    <div class="alert alert-danger">
      <%= flash[:danger] %>
    </div>
    <% end %>

    <%= yield %>
  <%= render 'layouts/footer' %>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<!-- Ajout d'un avatar-->
<div class="text-center">
  <h3 class="mt-3">Avatar actuel pour l'utilisateur <%=@user.id%></h3>
  <%if @user.avatar.attached?%>
    <%= image_tag @user.avatar, alt: 'avatar' %>
  <%else%>
    <p>Il n'y a pas encore d'avatar lié à cet utilisateur</p>
  <%end%>

  <h4 class="mt-3">Souhaitez-vous changer d'avatar ?</h4>
    <%= form_tag user_avatars_path(@user), multipart: true do %>
    <%= file_field_tag :avatar %>
    <%= submit_tag "mettre à jour" %>
  <% end %>
</div>
<!-- Fin ajout d'avatar-->
</div>